import Link from "next/link";
import { LEGAL } from "@/lib/legal";

export const metadata = { title: "Terms — DevBrain" };

export default function Terms() {
  return (
    <main className="mx-auto max-w-2xl px-6 py-16 text-slate-800">
      <Link href="/" className="text-sm text-brand-600 hover:underline">← DevBrain</Link>
      <h1 className="mt-4 text-3xl font-semibold tracking-tight text-slate-900">Terms of Use</h1>
      <p className="mt-1 text-sm text-slate-500">Effective {LEGAL.effective}</p>

      <Section title="What DevBrain is">
        {LEGAL.product} is a coordination and memory tool for teams whose developers use coding agents.
        It is currently offered as-is, free of charge, and provided by {LEGAL.operator}.
      </Section>

      <Section title="Acceptable use">
        <ul className="ml-5 list-disc space-y-1.5">
          <li>Connect only repositories and accounts you are authorized to connect.</li>
          <li>Don&apos;t attempt to access another team&apos;s data, probe for vulnerabilities without
          permission, or disrupt the service for others.</li>
          <li>Don&apos;t use the service to process content you are not permitted to send to a third-party
          AI provider (see the Privacy page for what is sent).</li>
        </ul>
      </Section>

      <Section title="AI-generated content">
        PR reviews, journal summaries, and task suggestions are generated by an AI model and may be
        incomplete or wrong. They are aids, not authoritative judgments — a green merge light is a
        signal, never a guarantee, and you remain responsible for what you merge and ship.
      </Section>

      <Section title="Availability &amp; limits">
        The service may change, pause, or impose usage limits (including AI-call caps) without notice.
        Being free and early, it comes with no uptime commitment and may have outages or data issues.
      </Section>

      <Section title="No warranty; limitation of liability">
        The service is provided &quot;as is&quot;, without warranties of any kind. To the maximum extent
        permitted by law, {LEGAL.operator} are not liable for any damages arising from your use of it,
        including lost work, missed collisions, or incorrect AI output. Keep your own backups and code
        review; DevBrain assists your process, it does not replace it.
      </Section>

      <Section title="Termination">
        You may stop using DevBrain at any time by unlinking your repositories and leaving your teams.
        We may suspend access that violates these terms or endangers the service.
      </Section>

      <Section title="Contact">
        {LEGAL.contact}.
      </Section>

      <p className="mt-10 border-t border-slate-200 pt-4 text-xs text-slate-400">
        A plain-language draft for an early, free product. Not legal advice; subject to change.
      </p>
    </main>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mt-8">
      <h2 className="text-lg font-semibold text-slate-900">{title}</h2>
      <div className="mt-2 text-sm leading-relaxed text-slate-700">{children}</div>
    </section>
  );
}
